don_gia = int(input("Nhập giá: "))
ma_giam_gia = input("Nhập mã giảm giá: ")
phan_tram_giam = int(ma_giam_gia[-2:])
# so_tien_duoc_giam = int(phan_tram_giam*don_gia/100)
tong_tien = int( don_gia*(1 - phan_tram_giam/100) )
print(f"Đơn giá: {don_gia}")
print(f"Mã gỉm giá: {ma_giam_gia}")
print(f"Giảm giá: {phan_tram_giam}%")
print(f"Tổng tiền phải trả: {tong_tien}")